# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2023-10-23 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldRelation',
            fields=[
                ('field_id', models.AutoField(db_column='fieldId', primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='fieldName', max_length=255)),
            ],
            options={
                'db_table': 'fieldsrelations',
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('alias', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('reference', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'namespaces',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(db_column='nodeId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdfserializer.Namespace')),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('creator', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uri', models.URLField()),
            ],
            options={
                'db_table': 'schemes',
            },
        ),
        migrations.AddField(
            model_name='fieldrelation',
            name='node',
            field=models.ForeignKey(db_column='nodeId', on_delete=django.db.models.deletion.CASCADE, to='rdfserializer.Node'),
        ),
    ]
