# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomicclassifiertyperequest',
            options={'managed': False, 'verbose_name': 'Taxonomic Classifier Type Request'},
        ),
        migrations.AlterModelTable(
            name='actiontype',
            table='actiontypecv',
        ),
        migrations.AlterModelTable(
            name='actiontyperequest',
            table='actiontypecvrequests',
        ),
        migrations.AlterModelTable(
            name='aggregationstatistic',
            table='aggregationstatisticcv',
        ),
        migrations.AlterModelTable(
            name='aggregationstatisticrequest',
            table='aggregationstatisticcvrequests',
        ),
        migrations.AlterModelTable(
            name='annotationtype',
            table='annotationtypecv',
        ),
        migrations.AlterModelTable(
            name='annotationtyperequest',
            table='annotationtypecvrequests',
        ),
        migrations.AlterModelTable(
            name='censorcode',
            table='censorcodecv',
        ),
        migrations.AlterModelTable(
            name='censorcoderequest',
            table='censorcodecvrequests',
        ),
        migrations.AlterModelTable(
            name='datasettype',
            table='datasettypecv',
        ),
        migrations.AlterModelTable(
            name='datasettyperequest',
            table='datasettypecvrequests',
        ),
        migrations.AlterModelTable(
            name='directivetype',
            table='directivetypecv',
        ),
        migrations.AlterModelTable(
            name='directivetyperequest',
            table='directivetypecvrequests',
        ),
        migrations.AlterModelTable(
            name='elevationdatum',
            table='elevationdatumcv',
        ),
        migrations.AlterModelTable(
            name='elevationdatumrequest',
            table='elevationdatumcvrequests',
        ),
        migrations.AlterModelTable(
            name='equipmenttype',
            table='equipmenttypecv',
        ),
        migrations.AlterModelTable(
            name='equipmenttyperequest',
            table='equipmenttypecvrequests',
        ),
        migrations.AlterModelTable(
            name='methodtype',
            table='methodtypecv',
        ),
        migrations.AlterModelTable(
            name='methodtyperequest',
            table='methodtypecvrequests',
        ),
        migrations.AlterModelTable(
            name='organizationtype',
            table='organizationtypecv',
        ),
        migrations.AlterModelTable(
            name='organizationtyperequest',
            table='organizationtypecvrequests',
        ),
        migrations.AlterModelTable(
            name='propertydatatype',
            table='propertydatatypecv',
        ),
        migrations.AlterModelTable(
            name='propertydatatyperequest',
            table='propertydatatypecvrequests',
        ),
        migrations.AlterModelTable(
            name='qualitycode',
            table='qualitycodecv',
        ),
        migrations.AlterModelTable(
            name='qualitycoderequest',
            table='qualitycodecvrequests',
        ),
        migrations.AlterModelTable(
            name='referencematerialmedium',
            table='referencematerialmediumcv',
        ),
        migrations.AlterModelTable(
            name='referencematerialmediumrequest',
            table='referencematerialmediumcvrequests',
        ),
        migrations.AlterModelTable(
            name='resulttype',
            table='resulttypecv',
        ),
        migrations.AlterModelTable(
            name='resulttyperequest',
            table='resulttypecvrequests',
        ),
        migrations.AlterModelTable(
            name='sampledmedium',
            table='sampledmediumcv',
        ),
        migrations.AlterModelTable(
            name='sampledmediumrequest',
            table='sampledmediumcvrequests',
        ),
        migrations.AlterModelTable(
            name='samplingfeaturegeotype',
            table='samplingfeaturegeotypecv',
        ),
        migrations.AlterModelTable(
            name='samplingfeaturegeotyperequest',
            table='samplingfeaturegeotypecvrequests',
        ),
        migrations.AlterModelTable(
            name='samplingfeaturetype',
            table='samplingfeaturetypecv',
        ),
        migrations.AlterModelTable(
            name='samplingfeaturetyperequest',
            table='samplingfeaturetypecvrequests',
        ),
        migrations.AlterModelTable(
            name='sitetype',
            table='sitetypecv',
        ),
        migrations.AlterModelTable(
            name='sitetyperequest',
            table='sitetypecvrequests',
        ),
        migrations.AlterModelTable(
            name='spatialoffsettype',
            table='spatialoffsettypecv',
        ),
        migrations.AlterModelTable(
            name='spatialoffsettyperequest',
            table='spatialoffsettypecvrequests',
        ),
        migrations.AlterModelTable(
            name='speciation',
            table='speciationcv',
        ),
        migrations.AlterModelTable(
            name='speciationrequest',
            table='speciationcvrequests',
        ),
        migrations.AlterModelTable(
            name='specimenmedium',
            table='specimenmediumcv',
        ),
        migrations.AlterModelTable(
            name='specimenmediumrequest',
            table='specimenmediumcvrequests',
        ),
        migrations.AlterModelTable(
            name='specimentype',
            table='specimentypecv',
        ),
        migrations.AlterModelTable(
            name='specimentyperequest',
            table='specimentypecvrequests',
        ),
        migrations.AlterModelTable(
            name='status',
            table='statuscv',
        ),
        migrations.AlterModelTable(
            name='statusrequest',
            table='statuscvrequests',
        ),
        migrations.AlterModelTable(
            name='taxonomicclassifiertype',
            table='taxonomicclassifiertypecv',
        ),
        migrations.AlterModelTable(
            name='taxonomicclassifiertyperequest',
            table='taxonomicclassifiertypecvrequests',
        ),
        migrations.AlterModelTable(
            name='variablename',
            table='variablenamecv',
        ),
        migrations.AlterModelTable(
            name='variablenamerequest',
            table='variablenamecvrequests',
        ),
        migrations.AlterModelTable(
            name='variabletype',
            table='variabletypecv',
        ),
        migrations.AlterModelTable(
            name='variabletyperequest',
            table='variabletypecvrequests',
        ),
    ]
