# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
                ('produces_result', models.CharField(blank=True, max_length=5, db_column='producesResult', choices=[('Yes', 'Yes'), ('No', 'No')])),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Action Type',
                'db_table': 'actiontypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActionTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
                ('produces_result', models.CharField(blank=True, max_length=5, db_column='producesResult', choices=[('Yes', 'Yes'), ('No', 'No')])),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Action Type Request',
                'db_table': 'actiontypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggregationStatistic',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aggregation Statistic',
                'db_table': 'aggregationstatisticcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggregationStatisticRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Aggregation Statistic Request',
                'db_table': 'aggregationstatisticcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Annotation Type',
                'db_table': 'annotationtypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Annotation Type Request',
                'db_table': 'annotationtypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensorCode',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Censor Code',
                'db_table': 'censorcodecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CensorCodeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Censor Code Request',
                'db_table': 'censorcodecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataQualityType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Data Quality Type',
                'db_table': 'dataqualitytypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataQualityTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Data Quality Type Request',
                'db_table': 'dataqualitytypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dataset Type',
                'db_table': 'datasettypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Dataset Type Request',
                'db_table': 'datasettypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectiveType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Directive Type',
                'db_table': 'directivetypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectiveTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Directive Type Request',
                'db_table': 'directivetypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElevationDatum',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Elevation Datum',
                'db_table': 'elevationdatumcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElevationDatumRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Elevation Datum Request',
                'db_table': 'elevationdatumcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'db_table': 'equipmenttypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Equipment Type Request',
                'db_table': 'equipmenttypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MethodType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Method Type',
                'db_table': 'methodtypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MethodTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Method Type Request',
                'db_table': 'methodtypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Organization Type',
                'db_table': 'organizationtypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Organization Type Request',
                'db_table': 'organizationtypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDataType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Property Data Type',
                'db_table': 'propertydatatypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyDataTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Property Data Type Request',
                'db_table': 'propertydatatypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualityCode',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Quality Code',
                'db_table': 'qualitycodecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualityCodeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Quality Code Request',
                'db_table': 'qualitycodecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceMaterialMedium',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Reference Material Medium',
                'db_table': 'referencematerialmediumcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceMaterialMediumRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Reference Material Medium Request',
                'db_table': 'referencematerialmediumcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Relationship Type',
                'db_table': 'relationshiptypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Relationship Type Request',
                'db_table': 'relationshiptypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Result Type',
                'db_table': 'resulttypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Result Type Request',
                'db_table': 'resulttypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampledMedium',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sampled Medium',
                'db_table': 'sampledmediumcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampledMediumRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Sampled Medium Request',
                'db_table': 'sampledmediumcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingFeatureGeotype',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Sampling Feature Geo-type',
                'db_table': 'samplingfeaturegeotypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingFeatureGeotypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Sampling Feature Geo-type Request',
                'db_table': 'samplingfeaturegeotypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingFeatureType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sampling Feature Type',
                'db_table': 'samplingfeaturetypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingFeatureTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Sampling Feature Type Request',
                'db_table': 'samplingfeaturetypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Type',
                'db_table': 'sitetypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Site Type Request',
                'db_table': 'sitetypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialOffsetType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
                ('offset1', models.TextField(db_column='offset1', blank=True)),
                ('offset2', models.TextField(db_column='offset2', blank=True)),
                ('offset3', models.TextField(db_column='offset3', blank=True)),
            ],
            options={
                'verbose_name': 'Spatial Offset Type',
                'db_table': 'spatialoffsettypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialOffsetTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
                ('offset1', models.TextField(db_column='offset1', blank=True)),
                ('offset2', models.TextField(db_column='offset2', blank=True)),
                ('offset3', models.TextField(db_column='offset3', blank=True)),
            ],
            options={
                'verbose_name': 'Spatial Offset Type Request',
                'db_table': 'spatialoffsettypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Speciation',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Speciation',
                'db_table': 'speciationcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciationRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Speciation Request',
                'db_table': 'speciationcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecimenMedium',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Specimen Medium',
                'db_table': 'specimenmediumcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecimenMediumRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Specimen Medium Request',
                'db_table': 'specimenmediumcvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecimenType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Specimen Type',
                'db_table': 'specimentypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecimenTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Specimen Type Request',
                'db_table': 'specimentypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Status',
                'db_table': 'statuscv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Status Request',
                'db_table': 'statuscvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomicClassifierType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Taxonomic Classifier Type',
                'db_table': 'taxonomicclassifiertypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomicClassifierTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Taxonomic Classifier Type Request',
                'db_table': 'taxonomicclassifiertypecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableName',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Variable Name',
                'db_table': 'variablenamecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableNameRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Variable Name Request',
                'db_table': 'variablenamecvrequests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('term', models.CharField(max_length=255, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('category', models.CharField(max_length=255, blank=True)),
                ('provenance', models.TextField(blank=True)),
                ('provenance_uri', models.URLField(db_column='provenanceUri', blank=True)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Variable Type',
                'db_table': 'variabletypecv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariableTypeRequest',
            fields=[
                ('term', models.CharField(help_text='Please enter a URI-friendly version of your term with no spaces, special characters, etc.', max_length=255)),
                ('name', models.CharField(help_text='Please enter the term as you would expect it to appear in a sentence.', max_length=255)),
                ('definition', models.TextField(help_text='Please enter a detailed definition of the term.')),
                ('category', models.CharField(help_text='You may suggest a category for the term. Refer to the vocabulary to see which categories have been used. You may also suggest a new category.', max_length=255, blank=True)),
                ('provenance', models.TextField(help_text='Enter a note about where the term came from. If you retrieved the definition of the term from a website or other source, note that here.', blank=True)),
                ('provenance_uri', models.URLField(help_text='If you retrieved the term from another formal vocabulary system, enter the URI of the term from the other system here.', db_column='provenanceUri', blank=True)),
                ('note', models.TextField(help_text='Please enter any additional notes you may have about the term.', blank=True)),
                ('request_id', models.CharField(default=uuid.uuid4, max_length=255, serialize=False, primary_key=True, db_column='requestId')),
                ('status', models.CharField(default='Pending', max_length=255, db_column='status', choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')])),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, db_column='dateSubmitted')),
                ('date_status_changed', models.DateField(default=django.utils.timezone.now, db_column='dateStatusChanged')),
                ('request_notes', models.TextField(db_column='requestNotes', blank=True)),
                ('submitter_name', models.CharField(help_text='Enter your name.', max_length=255, db_column='submitterName')),
                ('submitter_email', models.CharField(help_text='Enter your email address.', max_length=255, db_column='submitterEmail')),
                ('request_reason', models.CharField(help_text='Please enter a brief description of the reason for your submission (e.g., Term does not exist yet, Term is needed for my data use case, etc.)', max_length=255, db_column='requestReason')),
            ],
            options={
                'verbose_name': 'Variable Type Request',
                'db_table': 'variabletypecvrequests',
                'managed': False,
            },
        ),
    ]
